name: Publish RHDH Release Dynamic Plugin Images 
on:
  workflow_call:

  push:
    branches:
      - 'release-**'

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  export:
    uses: davidfestal/rhdh-dynamic-plugin-export-overlays/.github/workflows/export-workspaces-as-dynamic.yaml@main
    with:
      publish-container: true
      image-repository-prefix: ghcr.io/${{ github.repository }}
    permissions:
      contents: write
      attestations: write
      packages: write
      id-token: write