name: Publish PR Dynamic Plugins as Images 
on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  statuses: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare

    if: github.event.issue.pull_request
    outputs:
      overlay-branch: ${{ steps.get-branch.outputs.overlay-branch }}
      overlay-commit: ${{ steps.get-branch.outputs.overlay-commit }}
      workspace: ${{ steps.get-branch.outputs.workspace }}

    steps:
      - name: Get PR branch data
        id: get-branch
        uses: actions/github-script@v7
        with:
          script: |
            if ('${{ github.event.comment.body }}' !== '/publish') {
              return;
            }
            const currentPullRequest = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const prBranch = currentPullRequest.data.head.ref;
            const prCommit = currentPullRequest.data.head.sha;
            core.setOutput('overlay-commit', prCommit);
            let workspace = '';

            const matches = prBranch.match(/^workspaces\/release-.+__(.+)$/);
            if (matches && matches.length == 2) {
              workspace = `workspaces/${matches[1]}`;
            } else {
              const prFiles = await github.rest.pulls.listFiles({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number
              });
              const workspaces = [ ... new Set(prFiles.data
                .map(f => f.filename.match(/^workspaces\/([^\/]+)\/.*/))
                .filter(match => match)
                .map(match => match[1])
              )];
              if (workspaces.length === 1) {
                workspace =`workspaces/${workspaces[0]}`;
              }
            }
            core.setOutput('workspace', workspace);
            if (workspace === '') {
              return;
            }

            const workflowRun = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: '${{ github.run_id }}',
            });
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: prCommit,
              description: workflowRun.data.display_title,
              state: 'pending',
              target_url: workflowRun.html_url
            });
            
  parent_export:
    needs:
      - prepare

    if: needs.prepare.outputs.overlay-branch != '' && needs.prepare.outputs.workspace != ''

    uses: davidfestal/rhdh-plugin-export-utils/.github/workflows/export-workspaces-as-dynamic.yaml@multi-plugins-repo
    with:
      overlay-branch: ${{ needs.prepare.outputs.overlay-branch }}
      workspace-path: ${{ needs.prepare.outputs.workspace }}
      publish-container: true

    permissions:
      contents: write
      attestations: write
      packages: write
      id-token: write

  add_completion_comment:
    needs:
      - prepare
      - parent_export

    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Add success comment
        uses: actions/github-script@v7
        with:
          script: |
            const workflowRun = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: '${{ github.run_id }}',
            });
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: ${{ needs.prepare.outputs.overlay-commit }},
              description: workflowRun.data.display_title,
              state: workflowRun.data.conclusion === 'success' ?
                'success' : 'failure',
              target_url: workflowRun.html_url
            });

            let body = `Publish workflow finished:
            - published container images:
            ${{ needs.parent_export.outputs.published-exports }}            
            `;
            if ('${{ needs.parent_export.outputs.failed-exports }}' !== '') {
              body += `
            - failed exports:
            ${{ needs.parent_export.outputs.failed-exports }}            
            `;
            }

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
    
    permissions:
      pull-requests: write

  add_no_workspace_comment:
    needs:
      - prepare

    if: always() && needs.prepare.outputs.overlay-branch != '' && needs.prepare.outputs.workspace == ''
    runs-on: ubuntu-latest
    steps:
      - name: Add success comment
        uses: actions/github-script@v7
        with:
          script: |
            const body = 'Publish action cancelled: PR doesn't touch only 1 workspace';
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })       

    permissions:
      pull-requests: write

        